allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  minimatch@3.1.2: ^9.0.0
  glob: '>=11.1.0'
  undici: '>=6.24.0'
  effect: '>=3.20.0'
  defu: '>=6.1.5'
  picomatch: '>=4.0.4'
  brace-expansion@1: ^1.1.13
  brace-expansion@2: ^2.0.3
  brace-expansion@5: ^5.0.5
  '@tootallnate/once': '>=3.0.1'
