##### DEVELOPMENT DOCKER IMAGE
##### DEPENDENCIES
FROM --platform=linux/amd64 node:lts-alpine
RUN apk add --no-cache libc6-compat openssl openssl-dev
WORKDIR /app
RUN yarn global add pnpm ts-node

##### ENV_VARS
ARG DATABASE_URL=${DATABASE_URL}
ENV DATABASE_URL=${DATABASE_URL}
ENV NODE_ENV=development
ENV NEXTAUTH_URL=${NEXTAUTH_URL:-http://127.0.0.1}
ENV PORT=80
ENV NEXT_TELEMETRY_DISABLED=1

##### FILES
COPY ../prisma ./
COPY ../package.json ./
COPY ../pnpm-lock.yaml ./
RUN pnpm install

EXPOSE 80

CMD ["./start.dev.sh"]
