server {
        listen 80;
        listen [::]:80;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name 0.0.0.0;

        add_header X-Content-Type-Options  "nosniff"                          always;
        add_header X-Frame-Options         "SAMEORIGIN"                       always;
        add_header Referrer-Policy         "strict-origin-when-cross-origin"  always;

        location / {
                proxy_pass http://hytky:3000;
        }

        location ~ /.well-known/acme-challenge {
                allow all;
                root /var/www/html;
        }
}
