name: Create and publish a Docker image
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/hytky

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Get current branch and exit if not main
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "{name}=branch" >> $GITHUB_OUTPUT
          echo "Branch is $branch."
          if [ "$branch" != "main" ]; then
            echo "Not on main branch, exiting."
            exit 0
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7.1.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/Dockerfile.prod
          secrets: | # pass insensitive buildtime variables to docker
            "NEXT_PUBLIC_TG_BOT_NAME=${{ vars.NEXT_PUBLIC_TG_BOT_NAME }}"
            "NEXT_PUBLIC_TG_INFO_CHANNEL=${{ vars.NEXT_PUBLIC_TG_INFO_CHANNEL }}"

  deploy:
    name: Deploy to Production
    needs: build-and-push-image
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Pull and restart updated containers
        uses: appleboy/ssh-action@v1.2.5
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
        with:
          host: hytky.org
          username: dettmann
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          envs: DOMAIN
          script: |
            until curl -sf https://hytky.org/api/health; do sleep 10; done
            sudo git -C /opt/webapp checkout docker/nginx-conf/user_conf.d/tls.conf
            sudo git -C /opt/webapp pull
            sudo sed -i "s/sub.yourdomain.org/$DOMAIN www.$DOMAIN/g" /opt/webapp/docker/nginx-conf/user_conf.d/tls.conf
            cd /opt/webapp/docker
            docker compose --env-file /opt/webapp/.env -f docker-compose.prod.tls-registry.yml pull
            docker compose --env-file /opt/webapp/.env -f docker-compose.prod.tls-registry.yml up -d --remove-orphans
            docker compose --env-file /opt/webapp/.env -f docker-compose.prod.tls-registry.yml restart nginx
