name: ESLint Check

on:
  push:
    paths-ignore:
      - 'infrastructure/**'
      - 'ansible/**'
      - 'docs/**'
      - '**.md'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'infrastructure/**'
      - 'ansible/**'
      - 'docs/**'
      - '**.md'
      - '.github/**'

permissions:
  contents: read

jobs:
  eslint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g pnpm@10 && pnpm install

      - name: Run ESLint
        env:
          DATABASE_URL: postgres://postgres:examplechangeme@postgres:5432/postgres
          NEXTAUTH_SECRET: dummy_value
          NEXTAUTH_URL: http://localhost:80
          TG_BOT_TOKEN: dummy_value
          FORUM_ROOT_NAME: dummy_value
          NEXT_PUBLIC_TG_BOT_NAME: dummy_value
          NEXT_PUBLIC_TG_INFO_CHANNEL: https://google.com
        run: pnpm exec eslint . --ext .js,.jsx,.ts,.tsx
